package com.example.movieapp.model

data class Movie(
    val id: String,
    val title: String,
    val year: String,
    val genre: String,
    val director: String,
    val actor: String,
    val plot: String,
    val poster: String,
    val images: List<String>,
    val rating: String
)

fun getMovies(): List<Movie> {
    return listOf(
        Movie(
            id = "1",
            title = "The Shawshank Redemption",
            year = "1994",
            genre = "Drama",
            director = "Frank Darabont",
            actor = "Tim Robbins, Morgan Freeman",
            plot = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
            poster = "https://www.imdb.com/title/tt0111161/mediaviewer/rm1690056449/?ref_=tt_ov_i",
            images = listOf("https://www.imdb.com/title/tt0111161/mediaviewer/rm3789996032/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0111161/mediaviewer/rm3789996032/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0111161/mediaviewer/rm3789996032/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0111161/mediaviewer/rm3789996032/?ref_=tt_ov_i"),
            rating = "9.3"
        ),
        Movie(
            id = "2",
            title = "The Godfather",
            year = "1972",
            genre = "Crime, Drama",
            director = "Francis Ford Coppola",
            actor = "Marlon Brando, Al Pacino",
            plot = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
            poster = "https://www.imdb.com/title/tt0068646/mediaviewer/rm746868224/?ref_=tt_ov_i",
            images = listOf("https://www.imdb.com/title/tt0068646/mediaviewer/rm2120732160/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0068646/mediaviewer/rm2120732160/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0068646/mediaviewer/rm2120732160/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0068646/mediaviewer/rm2120732160/?ref_=tt_ov_i"),
            rating = "9.2"
        ),
        Movie(
            id = "3",
            title = "The Dark Knight",
            year = "2008",
            genre = "Action, Crime, Drama",
            director = "Christopher Nolan",
            actor = "Christian Bale, Heath Ledger",
            plot = "When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
            poster = "https://www.imdb.com/title/tt0468569/mediaviewer/rm4023877632/?ref_=tt_ov_i",
            images = listOf("https://www.imdb.com/title/tt0468569/mediaviewer/rm2097994240/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0468569/mediaviewer/rm2097994240/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0468569/mediaviewer/rm2097994240/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0468569/mediaviewer/rm2097994240/?ref_=tt_ov_i"),
            rating = "9.0"
        ),
        Movie(
            id = "4",
            title = "Pulp Fiction",
            year = "1994",
            genre = "Crime, Drama",
            director = "Quentin Tarantino",
            actor = "John Travolta, Uma Thurman",
            plot = "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
            poster = "https://www.imdb.com/title/tt0110912/mediaviewer/rm1959540736/?ref_=tt_ov_i",
            images = listOf("https://www.imdb.com/title/tt0110912/mediaviewer/rm1263589632/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0110912/mediaviewer/rm1263589632/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0110912/mediaviewer/rm1263589632/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0110912/mediaviewer/rm1263589632/?ref_=tt_ov_i"),
            rating = "8.9"
        ),
        Movie(
            id = "5",
            title = "Forrest Gump",
            year = "1994",
            genre = "Drama, Romance",
            director = "Robert Zemeckis",
            actor = "Tom Hanks, Robin Wright",
            plot = "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
            poster = "https://www.imdb.com/title/tt0109830/mediaviewer/rm4127741184/?ref_=tt_ov_i",
            images = listOf("https://www.imdb.com/title/tt0109830/mediaviewer/rm2749470208/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0109830/mediaviewer/rm2749470208/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0109830/mediaviewer/rm2749470208/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0109830/mediaviewer/rm2749470208/?ref_=tt_ov_i"),
            rating = "8.8"
        ),
        Movie(
            id = "6",
            title = "Inception",
            year = "2010",
            genre = "Action, Adventure, Sci-Fi",
            director = "Christopher Nolan",
            actor = "Leonardo DiCaprio, Joseph Gordon-Levitt",
            plot = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
            poster = "https://www.imdb.com/title/tt1375666/mediaviewer/rm3426651392/?ref_=tt_ov_i",
            images = listOf("https://www.imdb.com/title/tt1375666/mediaviewer/rm2933292288/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt1375666/mediaviewer/rm2933292288/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt1375666/mediaviewer/rm2933292288/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt1375666/mediaviewer/rm2933292288/?ref_=tt_ov_i"),
            rating = "8.8"
        ),
        Movie(
            id = "7",
            title = "Fight Club",
            year = "1999",
            genre = "Drama",
            director = "David Fincher",
            actor = "Brad Pitt, Edward Norton",
            plot = "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
            poster = "https://www.imdb.com/title/tt0137523/mediaviewer/rm1763020800/?ref_=tt_ov_i",
            images = listOf("https://www.imdb.com/title/tt0137523/mediaviewer/rm2810249728/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0137523/mediaviewer/rm2810249728/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0137523/mediaviewer/rm2810249728/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0137523/mediaviewer/rm2810249728/?ref_=tt_ov_i"),
            rating = "8.8"
        ),
        Movie(
            id = "8",
            title = "The Matrix",
            year = "1999",
            genre = "Action, Sci-Fi",
            director = "Lana Wachowski, Lilly Wachowski",
            actor = "Keanu Reeves, Laurence Fishburne",
            plot = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
            poster = "https://www.imdb.com/title/tt0133093/mediaviewer/rm300947200/?ref_=tt_ov_i",
            images = listOf("https://www.imdb.com/title/tt0133093/mediaviewer/rm1139985152/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0133093/mediaviewer/rm1139985152/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0133093/mediaviewer/rm1139985152/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0133093/mediaviewer/rm1139985152/?ref_=tt_ov_i"),
            rating = "8.7"
        ),
        Movie(
            id = "9",
            title = "The Lord of the Rings: The Return of the King",
            year = "2003",
            genre = "Action, Adventure, Drama",
            director = "Peter Jackson",
            actor = "Elijah Wood, Viggo Mortensen",
            plot = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
            poster = "https://www.imdb.com/title/tt0167260/mediaviewer/rm3527067648/?ref_=tt_ov_i",
            images = listOf("https://www.imdb.com/title/tt0167260/mediaviewer/rm221661184/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0167260/mediaviewer/rm221661184/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0167260/mediaviewer/rm221661184/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0167260/mediaviewer/rm221661184/?ref_=tt_ov_i"),
            rating = "8.9"
        ),
        Movie(
            id = "10",
            title = "The Silence of the Lambs",
            year = "1991",
            genre = "Crime, Drama, Thriller",
            director = "Jonathan Demme",
            actor = "Jodie Foster, Anthony Hopkins",
            plot = "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to catch another serial killer, a madman who skins his victims.",
            poster = "https://www.imdb.com/title/tt0102926/mediaviewer/rm2213194240/?ref_=tt_ov_i",
            images = listOf("https://www.imdb.com/title/tt0102926/mediaviewer/rm367237120/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0102926/mediaviewer/rm367237120/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0102926/mediaviewer/rm367237120/?ref_=tt_ov_i",
                "https://www.imdb.com/title/tt0102926/mediaviewer/rm367237120/?ref_=tt_ov_i"),
            rating = "8.6"
        )
    )
}
